apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
  namespace: tasky-lab
type: Opaque
stringData:
  MONGODB_URI: "mongodb://taskyappuser:<MONGO_APP_PASSWORD>@<MONGO_PRIVATE_IP>:27017/go-mongodb?authSource=go-mongodb"
  SECRET_KEY: "<TASKY_SECRET_KEY>"
